### ISSUE TITLE
Overlay not showing on 0.6.1

### ISSUE THREAD

**Issue by Schaloth** [cedricdsc/poe-instant-messenger#20]
## Expected Behavior

Overlay should have opened

## Current Behavior

Overlay not showing. Everything was fine on 0.6.0 but when I install 0.6.1 or update from 0.6.1 overlay not showing

## Steps to Reproduce

1.

2.

3.

## Your Environment

- Poe Instant Messenger version : 0.6.1
- Operating System: Windows 10
For (Devs)
- Node version:

**Comment by cedricdsc** [comment]
I'll look into this later today. Haven't had the issue myself yet. Sorry for any inconvenience!

**Comment by cedricdsc** [comment]
To keep you up to date: I found the problem and came up with a solution. The reason was I somehow managed to look over the fact that a native dependency was loaded in the renderer (the overlay) which is something that straight up won't work. 

Fix (v0.6.2) will soon be deployed and your app should download and install it on it's own on startup.
